config/routes.rb
Rails.application.routes.draw do
  get 'contact/index'
  get 'detail/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders
  resources :line_products
  resources :line_pros
  get 'home/index'
  resources :line_items
  resources :carts
  get 'store/index'
  resources :types
  resources :providers
  resources :products
  resources :combos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root :to => 'home#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, :dependent => :destroy
    
    def add_product(product_id)
        current_item = line_items.find_by_product_id(product_id)
        if current_item
          current_item.quantity += 1
        else
          current_item = line_items.build(:product_id => product_id)
          current_item.quantity = 1
        end
        current_item
    end

    def total_price 
      line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/combo.rb
class Combo < ApplicationRecord
    has_many :providers
    has_many :products, :through => :providers
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart 
    belongs_to :order, :optional => true


    def total_price
        product.price * quantity
    end
end

app/models/line_pro.rb
class LinePro < ApplicationRecord
end

app/models/line_product.rb
class LineProduct < ApplicationRecord
    belongs_to :product
    belongs_to :cart 
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, :dependent => :destroy
    PAYMENT_TYPES = [ "Tiền mặt", "Thẻ Visa/master", "Chuyển khoản" ]

    def add_line_items_from_cart(cart) 
        cart.line_items.each do |item|
            item.cart_id = nil
            line_items << item
        end
    end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :providers
    has_many :combos, :through => :providers
    belongs_to :type
    has_many :line_items
    before_destroy :ensure_not_referenced_by_any_line_item
    private
    def ensure_not_referenced_by_any_line_item
        if line_items.empty?
            return true
        else
            errors.add(:base, 'Line Items present')
            return false
        end
    end
end

app/models/provider.rb
class Provider < ApplicationRecord
    belongs_to :combo
    belongs_to :product
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :products
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to '/providers/new', notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:combo_id, :product_id)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/combos_helper.rb
module CombosHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/detail_helper.rb
module DetailHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/line_pros_helper.rb
module LineProsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/providers/_form.html.erb
<%= form_with(model: provider, local: true) do |form| %>
  <% if provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
        <% provider.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :combo_id %>
    <%= form.collection_select(:combo_id, Combo.all, :id, :name, prompt: true) %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.collection_select(:product_id, Product.all, :id, :name, prompt: true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/providers/edit.html.erb
<h1>Editing Provider</h1>

<%= render 'form', provider: @provider %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

app/views/providers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Providers</h1>

<table>
  <thead>
    <tr>
      <th>Combo</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= provider.combo_id %></td>
        <td><%= provider.product_id %></td>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provider', new_provider_path %>

app/views/providers/new.html.erb
<h1>New Provider</h1>

<%= render 'form', provider: @provider %>

<%= link_to 'Back', providers_path %>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Combo:</strong>
  <%= @provider.combo_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @provider.product_id %>
</p>

<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>