config/routes.rb
Rails.application.routes.draw do
  get 'contact/index'
  get 'detail/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders
  resources :line_products
  resources :line_pros
  get 'home/index'
  resources :line_items
  resources :carts
  get 'store/index'
  resources :types
  resources :providers
  resources :products
  resources :combos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root :to => 'home#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, :dependent => :destroy
    
    def add_product(product_id)
        current_item = line_items.find_by_product_id(product_id)
        if current_item
          current_item.quantity += 1
        else
          current_item = line_items.build(:product_id => product_id)
          current_item.quantity = 1
        end
        current_item
    end

    def total_price 
      line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/combo.rb
class Combo < ApplicationRecord
    has_many :providers
    has_many :products, :through => :providers
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart 
    belongs_to :order, :optional => true


    def total_price
        product.price * quantity
    end
end

app/models/line_pro.rb
class LinePro < ApplicationRecord
end

app/models/line_product.rb
class LineProduct < ApplicationRecord
    belongs_to :product
    belongs_to :cart 
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, :dependent => :destroy
    PAYMENT_TYPES = [ "Tiền mặt", "Thẻ Visa/master", "Chuyển khoản" ]

    def add_line_items_from_cart(cart) 
        cart.line_items.each do |item|
            item.cart_id = nil
            line_items << item
        end
    end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :providers
    has_many :combos, :through => :providers
    belongs_to :type
    has_many :line_items
    before_destroy :ensure_not_referenced_by_any_line_item
    private
    def ensure_not_referenced_by_any_line_item
        if line_items.empty?
            return true
        else
            errors.add(:base, 'Line Items present')
            return false
        end
    end
end

app/models/provider.rb
class Provider < ApplicationRecord
    belongs_to :combo
    belongs_to :product
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :products
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @types = Type.all
    type ||= params[:type]
    # @products = type.nil? ? Product.where(type_id: = 1 ) : Product.where(type_id: type)
     @products = type.nil? ? Product.all : Product.where(type_id: type)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :status, :image_url, :discount, :type_id)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/combos_helper.rb
module CombosHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/detail_helper.rb
module DetailHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/line_pros_helper.rb
module LineProsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, ['Sản phẩm mới', 'Sản phẩm được ưa thích', 'Sản phẩm bán chạy', 'N/A'], prompt: true%>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :discount %>
    <%= form.text_field :discount %>
  </div>

  <div class="field">
    <%= form.label :type_id %>
    <%= form.collection_select(:type_id, Type.all, :id, :type_food, prompt: true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<table>
  <tbody>
    <% @products.each do |product| %>
        <div class="entry">
          <div class = "images">
            <%= image_tag(product.image_url, :size => "240x220") %>      
          </div>

          <div class="price_line">
            <h3><%= product.name %></h3> 
              <span class="price"><%= product.price %></span>
              <%= button_to '+', line_items_path(:product_id => product) %>
          </div>

        </div>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @product.status %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @product.discount %>
</p>

<p>
  <strong>Type:</strong>
  <%= @product.type_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>